### ISSUE TITLE
Add Nim 1.4.4 and Nim 1.4.6 to conda-forge

### ISSUE THREAD

**Issue by btcross26** [conda-forge/nim-feedstock#7]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
@pb-cdunn 

With 1.4.6 just being released, is it possible to add Nim 1.4.4 and 1.4.6 (latest) official releases (or just the 1.4.6) to `conda-forge`? I can create a PR from a forked repo, but it's not completely clear whether I need to run `conda-smithy` from the instructions. If needed though, it seems easy enough just to change the version number and add a SHA. I also hesitated because I noticed in the lone closed issue of this repo that there seems to be some sort of automated `condo-forge-linter` that takes care of this.

I appreciate any feedback you have here. Thanks.

**Comment by pb-cdunn** [comment]
I'm no expert with "conda-forge". Look at recent pull-requests and do what those did.

I _think_ you simply update `meta.yml`, push to your own fork, and submit the PR.

* https://github.com/conda-forge/nim-feedstock/blob/master/recipe/meta.yaml

You'll need to recalculate `sha256`. (I use the UNIX tool `sha256sum`.

**Comment by btcross26** [comment]
Thanks @pb-cdunn .

I have created a pull request for 1.4.4 which appears to have passed all the CICD checks. Once that goes through, I will do the same for 1.4.6.

**Comment by btcross26** [comment]
Closing this issue. 1.4.4 is uploaded. I went ahead and added my name to the maintainers and will upload 1.4.6 shortly.
